---
title: "celery 여러개 구동시 생기는 문제"
date : 2020-08-26 13:19:30 -0400
categories: Python
---


```
ERROR/MainProcess] Received unregistered task of type 'scheduler.coin_price.get_coin_info'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?
```
celery 작업을 한개만 돌릴때에는 문제가 생기지 않았는데,

2개 이상을 작동시키면 기존에 동작하던곳 로그에 새로 동작한 작업이 들어오는데 등록되지 않은 작업이 들어온다고 나온다.

## 브로커

celery 는 작업을  broker 에게 전달하고, 브로커는 워커에게 작업을 전달하여 처리를 하게되는데

<img width="501" alt="스크린샷 2020-08-23 오후 1 13 50" src="https://user-images.githubusercontent.com/43875634/90970638-8af2ed80-e542-11ea-87e2-8c9eebe48501.png">

위 그림 처럼 한 작업당 한 워커가 수행해야하는데

내가 한 워커에 여러 작업들을 넣어버려서 생긴 문제 같다.

코드를 수정해 한 워커에 한 작업을 할당해주니 오류 없이 제대로 동작하였다.
